### ISSUE TITLE
User Interface Features

### ISSUE THREAD

**Issue by BobCochran** [hozn/freezingsaddles-aurelia#1]
Can you please let me know if you have a feature list for this? A statement of what you want the interface to do, and mockups of what it ought to look like? I was thinking that if you have a DropBox account, you could provide any documentation you might have through a public download link. This is not urgent. Take your time. 

Thanks

Bob

**Comment by hozn** [comment]
I have no documentation, no :)  The goal was to build an SPA based on the current UI.  My main goals were to make a richer charting/reporting interface and better photos gallery support.
